version: "3.8"
services:
  lhgi:
    build:
      context: ./app
    container_name: lhgi
    restart: always
    env_file:
      - ./app/.env
    environment:
      - FLASK_ENV=prod
      - VIRTUAL_HOST=lhgi.minipass.me
      - VIRTUAL_PORT=8889
      - LETSENCRYPT_HOST=lhgi.minipass.me
      - LETSENCRYPT_EMAIL=kdresdell@gmail.com
      - SITE_URL=https://lhgi.minipass.me
      - TZ=America/Toronto
    expose:
      - "8889"
    volumes:
      - ./app/instance:/app/instance
      - ./app/static/uploads:/app/static/uploads
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: minipass_env_proxy   # verify on VPS: docker network ls | grep proxy
