"""Add receipt_filename to Expense

Revision ID: 717386dae2a5
Revises: 1439cf1ae318
Create Date: 2025-06-03 20:58:41.879952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717386dae2a5'
down_revision = '1439cf1ae318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###
